[project]
name = "pipeline-edd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyspark>=3.5.0",
    "delta-spark>=3.0.0",
    "ruff>=0.1.9",
    "black>=23.12.1",
    "mypy>=1.8.0"
]
